name: Link Checker

on: [push, pull_request]

jobs:
  check-urls:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Check URLs
        uses: lycheeverse/lychee-action@v2
        with:
          args: readme.md --verbose --accept 200,403 --exclude www.linkedin.com/company/solidity-developer
