name: URLs

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check URLs
        uses: lycheeverse/lychee-action@v1
        with:
          args: readme.md --accept 200,403 --exclude www.linkedin.com/company/solidity-developer
