name: Lint
on:
  pull_request:
    branches: [main]
    paths:
      - 'readme.md'
permissions:
  contents: read
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6
        with:
          fetch-depth: 0
      - name: awesome-lint
        run: ./.github/workflows/repo_linter.sh
