on:
  pull_request:
    branches: [main]
    paths:
      - 'readme.md'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: awesome-lint
        run: |
          set -eo pipefail
          
          # Find the repo in the git diff
          REPOS=$(git diff origin/main -- readme.md | grep '^+' | grep -Eo 'https.*#readme' | sed 's/#readme//' || true)
          
          if [ -z "$REPOS" ]; then
            echo "No new link found in the format:  https://....#readme"
            exit 0
          fi
          
          # Lint each repo found
          while IFS= read -r REPO_TO_LINT; do
            if [ -n "$REPO_TO_LINT" ]; then
              echo "Linting $REPO_TO_LINT"
              npx awesome-lint "$REPO_TO_LINT"
            fi
          done <<< "$REPOS"
